name: app_ui
description: Shared Material3 theme and common widgets for MindIsle apps.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^1.1.1
  models:
    path: ../models
  progress_indicator_m3e: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
